### PR TITLE
NFTables: Add backwards compatibility for seperate IPv4 and IPv6 tables

### PR DESCRIPTION
**Pull request by svenauhagen**
NFtables uses the INET table for NAT and Firewall Rules which combines IPv4 and IPv6. Older systems might not have this option and use the ip/ip6 table instead.

This adds a flag to fall back to the ip/ip6 table style.

Signed-Off-By: Sven Auhagen <sven.auhagen@voleatech.de>

### CODE REVIEW

**Comment by miniupnp** [comment]
@ juampe can you have a look at this ? see #710

**Review by miniupnp — APPROVED** [review]
it look great !
@juampe does it works for you ?

**Comment by svenauhagen** [comment]
@juampe great, thank you for testing.
@miniupnp can you have a fresh look at the PR?

**Review by miniupnp — APPROVED** [review]
looks great !

**Pull request merged**
