### PR TITLE
miniupnpc/CMakeLists.txt: generate and install miniupnpc.pc

### LINKED ISSUE #574: 2.2.3: `install` target fails and missing .pc file
Looks like cmake fails in `install` target
```console
+ cd miniupnpc-2.2.3
+ DESTDIR=/home/tkloczko/rpmbuild/BUILDROOT/miniupnpc-2.2.3-2.fc35.x86_64
+ /usr/bin/cmake --install x86_64-redhat-linux-gnu
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/tkloczko/rpmbuild/BUILDROOT/miniupnpc-2.2.3-2.fc35.x86_64/usr/lib64/libminiupnpc.so.2.2.3
-- Installing: /home/tkloczko/rpmbuild/BUILDROOT/miniupnpc-2.2.3-2.fc35.x86_64/usr/lib64/libminiupnpc.so.17
-- Installing: /home/tkloczko/rpmbuild/BUILDROOT/miniupnpc-2.2.3-2.fc35.x86_64/usr/lib64/libminiupnpc.so
-- Installing: /home/tkloczko/rpmbuild/BUILDROOT/miniupnpc-2.2.3-2.fc35.x86_64/usr/lib64/cmake/miniupnpc/libminiupnpc-shared.cmake
-- Installing: /home/tkloczko/rpmbuild/BUILDROOT/miniupnpc-2.2.3-2.fc35.x86_64/usr/lib64/cmake/miniupnpc/libminiupnpc-shared-relwithdebinfo.cmake
CMake Error at x86_64-redhat-linux-gnu/cmake_install.cmake:110 (file):
  file INSTALL cannot find
  "/home/tkloczko/rpmbuild/BUILD/miniupnpc-2.2.3/miniupnpc.h": No such file
  or directory.
```
cmake as weel do not generate and install miniupnpc.pc file (main Makegule is no longer able to generate that file)
```console
[tkloczko@ss-desktop miniupnpc-2.2.3]$ make miniupnpc.pc
make: *** No rule to make target 'miniupnpc.pc'.  Stop.
```

### PR DESCRIPTION
**Pull request by miniupnp**
fixes #574

### CODE REVIEW

**Comment by miniupnp** [comment]
@kloczek can you check if it is OK regarding the `miniupnpc.pc` file ?

**Comment by barracuda156** [comment]
There is still a problem with a missing header, and install fails: https://github.com/miniupnp/miniupnp/issues/574#issuecomment-1077658534

**Comment by Biswa96** [comment]
The Description, URL and Version fields are empty in generated pkgconfig file. Those need to be added in `project()` function in main CMakeLists.txt file. Also, those quotes are not required generally.

**Comment by miniupnp** [comment]
@kloczek @Biswa96 is that OK ?

**Comment by kloczek** [comment]
Things like project name, description and URL provides cmake `project()` https://cmake.org/cmake/help/latest/command/project.html#command:project

**Comment by kloczek** [comment]
In other words you don;t need to define custom variables.

**Comment by miniupnp** [comment]
@kloczek is it better now ?

**Comment by kloczek** [comment]
[mode=garfild]
much better
[/mode]
😋

**Pull request merged**
