### PR TITLE
Remove default policies for nft chains

### PR DESCRIPTION
**Pull request by HarukaMa**
For #649. Feel free to close this if you think this is not desired.

### CODE REVIEW

**Comment by svenauhagen** [comment]
Hi, no you can not remove the default policy. If no policy is set nftables uses accept as policy which means all packets will be accepted even if there is no firewall rule for them. So this will just pass everything.

**Comment by HarukaMa** [comment]
is there a specific reason that miniupnpd *requires* a default reject on forward and accept on input and output? I don't quite think that miniupnpd should mandate what the default policies will be if it's not a hard requirement for it to function.Also the iptables backend is not enforcing this policy as well. Why it's only an issue on nft backend?Sent from my iPhoneOn Mar 22, 2023, at 13:13, sven ***@***.***> wrote:﻿
Hi, no you can not remove the default policy. If no policy is set nftables uses accept as policy which means all packets will be accepted even if there is no firewall rule for them. So this will just pass everything.

**Comment by svenauhagen** [comment]
miniupnpd requires a reject on forward because otherwise the firewall rules generated by miniupnpd would be useless.
All traffic would simply be forwarded no matter what rules are added.
miniupnpd is not creating any input or output chains, you can do that yourself if you like.
postrouting and prerouting are NAT chains and they are set to accept because otherwise all traffic would be dropped that has no DNAT or SNAT rule which is not what you want in a routing setup.
This would only allow traffic that has a matching miniupnpd rule in NAT to go out but you probably also want to allow other traffic to go out into the internet as well not only miniupnpd traffic.
You can always create your own matching ruleset if you like and change the chain names in the miniupnpd config if you have a different setup.

**Comment by HarukaMa** [comment]
> All traffic would simply be forwarded no matter what rules are added.

It doesn't affect the forwarding rules in the prerouting chain, no? Also I've removed the drop policy and miniupnpd is still forwarding incoming traffic without issue, so how is it required?

I just wanted to say that some configurations depend on the default policies to work; it should not be miniupnpd's job to decide what to do with other traffic that is not handled by miniupnpd, except when it's _absolutely required_ for the core functions to work, which I still fail to see why it's required.

Also I have to point it out again that the scripts for iptables backend is _not_ doing this.

**Comment by svenauhagen** [comment]
It still works because the default policy in nftables is accept. This will make the forward rules of miniupnpd useless though since everything will be accepted anyways. Also traffic from the Internet will have unrestricted access to your LAN so you might want to take that into consideration. For DNAT and SNAT there will be no change since miniupnpd sets the policy to accept also. This is to make sure there is a policy and we do not depend on whatever default is set in nftables. 
Iptables and nftables work fundamentally different as that Iptables gives you a pre created set of chains which in nftables you have to create from scratch with tables, chains and policy’s. That is why they are different. You do not have to use the default scripts though you can always write your own rulesets for miniupnpd and nftables. The design is flexible.

**Comment by HarukaMa** [comment]
Yeah, I'm already modifying the scripts locally as the default behavior is really disruptive for me. I think generally you don't want to make potentially disruptive changes to the network policies without notifying the users. (Docker changes the default policy to drop on the forwarding chain as well, and it's frowned upon by many, just FYI.)

I'll close this PR as it seems you are not really interested to change this.

**Pull request closed without merging**
