### PR TITLE
Hook up with Travis CI

### PR DESCRIPTION
**Pull request by Chocobo1**
Hook up with  [Travis CI](https://travis-ci.org).
I believe it's good for this project, i.e. you can make sure compilation is not broken when accepting a pull request.

If you are willing to merge this, please follow these steps:
1. Sign up on Travis CI, you can sign up via your github account.
2. Merge this pull request.
3. Change the link of the badge (first line in `Readme.md`) to your project URL on Travis CI.
4. Tick the settings on Travis CI to enable auto build for this project.
5. All Done!

### CODE REVIEW

**Comment by miniupnp** [comment]
Travis CI will really be useful when it supports multiple OS :)
I've added the "make check" for miniupnpc

**Comment by Chocobo1** [comment]
:fearful: I thought you weren't going to pull this in a short time. I made some changes to the script but didn't pushed yet.

Take a look at: https://github.com/Chocobo1/miniupnp/commit/462dd9bd516a3c19bd98b04a4049b26b25c7f8d0
Changes:
 * removed `git:  depth: 1`: this could break non-HEAD builds
 * interchange `env:` and `compiler:` sections: this will group project together, instead of compiler (on Travis-CI page)
 * `make -f $MAKEFILE -j3`: container-based has more CPU cores
 * move the make check under `after_success:` section: Only run tests when build success.

The container-builds won't work right now, because the packages isn't in their whitelist yet.
I've already made a request: https://github.com/travis-ci/travis-ci/issues/created_by/Chocobo1.


Last, you could add a link on the current page to the project on travis.

**Comment by miniupnp** [comment]
I had a little time to sign up on Travis CI.
I really hope they will had the necessary packages soon

**Comment by Chocobo1** [comment]
> I really hope they will had the necessary packages soon

Yeah.
I'll close this PR and leave the decision of merging my suggestion up to you.

**Comment by Chocobo1** [comment]
Seems TravisCI whitelisted the packages, all compiles are OK now.

**Comment by miniupnp** [comment]
It still fails for me, with the message *Disallowing packages: libnfnetlink-dev*

**Comment by miniupnp** [comment]
well yes it's ok now :)

**Comment by miniupnp** [comment]
@Chocobo1 do you know how NOT to build th "miniupnpd" project under OS X ?
It  doesn't build on recent OS X and will probably never
https://travis-ci.org/miniupnp/miniupnp/builds/80432465

**Pull request closed without merging**
