### PR TITLE
twine check wheels

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
@miniupnp, do you want to include the `README` as the long description?  If not, we can make some blank thing to retain existing metadata.

**Comment by miniupnp** [comment]
I don't understand why the appveyor generated win32 wheels are uploaded successfully. They don't include any long_description either...
```
diff -bru appveyor/miniupnpc-2.2.8.dist-info/LICENSE github_actions/miniupnpc-2.2.8.dist-info/LICENSE
--- appveyor/miniupnpc-2.2.8.dist-info/LICENSE  2024-06-08 22:59:20.000000000 +0200
+++ github_actions/miniupnpc-2.2.8.dist-info/LICENSE    2024-06-08 22:49:08.000000000 +0200
@@ -1 +1,29 @@
-../LICENSE
\ No newline at end of file
+BSD 3-Clause License
+
+Copyright (c) 2005-2024, Thomas BERNARD
+All rights reserved.
+
+Redistribution and use in source and binary forms, with or without
+modification, are permitted provided that the following conditions are met:
+
+1. Redistributions of source code must retain the above copyright notice, this
+   list of conditions and the following disclaimer.
+
+2. Redistributions in binary form must reproduce the above copyright notice,
+   this list of conditions and the following disclaimer in the documentation
+   and/or other materials provided with the distribution.
+
+3. Neither the name of the copyright holder nor the names of its
+   contributors may be used to endorse or promote products derived from
+   this software without specific prior written permission.
+
+THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
+FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
+SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
+CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
+OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
diff -bru appveyor/miniupnpc-2.2.8.dist-info/METADATA github_actions/miniupnpc-2.2.8.dist-info/METADATA
--- appveyor/miniupnpc-2.2.8.dist-info/METADATA 2024-06-08 22:59:20.000000000 +0200
+++ github_actions/miniupnpc-2.2.8.dist-info/METADATA   2024-06-08 22:49:08.000000000 +0200
@@ -5,6 +5,28 @@
 Home-page: https://miniupnp.tuxfamily.org/
 Author: Thomas BERNARD
 Author-email: miniupnp@free.fr
-License: ../LICENSE
+License: BSD 3-Clause License        
+        Copyright (c) 2005-2024, Thomas BERNARD
+        All rights reserved.        
+        Redistribution and use in source and binary forms, with or without
+        modification, are permitted provided that the following conditions are met:        
+        1. Redistributions of source code must retain the above copyright notice, this
+           list of conditions and the following disclaimer.        
+        2. Redistributions in binary form must reproduce the above copyright notice,
+           this list of conditions and the following disclaimer in the documentation
+           and/or other materials provided with the distribution.        
+        3. Neither the name of the copyright holder nor the names of its
+           contributors may be used to endorse or promote products derived from
+           this software without specific prior written permission.        
+        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+        AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
+        FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
+        SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
+        CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
+        OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.        
 License-File: LICENSE
 
diff -bru appveyor/miniupnpc-2.2.8.dist-info/RECORD github_actions/miniupnpc-2.2.8.dist-info/RECORD
--- appveyor/miniupnpc-2.2.8.dist-info/RECORD   2024-06-08 22:59:20.000000000 +0200
+++ github_actions/miniupnpc-2.2.8.dist-info/RECORD     2024-06-08 22:49:08.000000000 +0200
@@ -1,6 +1,6 @@
-miniupnpc.cp312-win_amd64.pyd,sha256=TSPoBKQhveniGBK-O6Fs4-WM9OIRuYf-1YKjwB5csHw,20992
-miniupnpc-2.2.8.dist-info/LICENSE,sha256=Hogezyhi0B5uW8K4YeRohtKm-wFJnAxQiiCacnGxPPI,10
-miniupnpc-2.2.8.dist-info/METADATA,sha256=NtPawp6-ABOdOAl3NBblIR27gsu7-hJ5RruFPdMehrA,232
-miniupnpc-2.2.8.dist-info/WHEEL,sha256=fZWyj_84lK0cA-ZNCsdwhbJl0OTrpWkxInEn424qrSs,102
+miniupnpc.cpython-310-x86_64-linux-gnu.so,sha256=SprVR0bbtOzC4RF8PHfJJyhZVsW-2aJBOCeGskruUyE,114784
+miniupnpc-2.2.8.dist-info/WHEEL,sha256=WtOPpVzyUQ5IjxtiZBzfCuF5fAyY4CBKenJ06AleLbg,152
+miniupnpc-2.2.8.dist-info/LICENSE,sha256=dICuI7CCwFrZgjiWFj1486lvG-rc5R8pyWz4mFRcJ-U,1527
 miniupnpc-2.2.8.dist-info/top_level.txt,sha256=MVW2jaDPL2mfALzkiwB3ENC3cOcJbD14tubOemmM408,10
 miniupnpc-2.2.8.dist-info/RECORD,,
+miniupnpc-2.2.8.dist-info/METADATA,sha256=kGRtBIrtlRhPsmkWTGe9Hh3s2TQofXoKO9NZzb04iK4,1964
diff -bru appveyor/miniupnpc-2.2.8.dist-info/WHEEL github_actions/miniupnpc-2.2.8.dist-info/WHEEL
--- appveyor/miniupnpc-2.2.8.dist-info/WHEEL    2024-06-08 22:59:20.000000000 +0200
+++ github_actions/miniupnpc-2.2.8.dist-info/WHEEL      2024-06-08 22:49:08.000000000 +0200
@@ -1,5 +1,6 @@
 Wheel-Version: 1.0
-Generator: bdist_wheel (0.43.0)
+Generator: bdist_wheel (0.37.1)
 Root-Is-Purelib: false
-Tag: cp312-cp312-win_amd64
+Tag: cp310-cp310-manylinux_2_12_x86_64
+Tag: cp310-cp310-manylinux2010_x86_64
 
Only in appveyor: miniupnpc.cp312-win_amd64.pyd
Only in github_actions: miniupnpc.cpython-310-x86_64-linux-gnu.so
Only in github_actions: miniupnpc.libs
```

**Comment by miniupnp** [comment]
> @miniupnp, do you want to include the `README` as the long description? If not, we can make some blank thing to retain existing metadata.

could you use the new `DESCRIPTION`  file ? f79ae6738d10af633844dcf3ecd9c587e8f9508d

**Comment by altendky** [comment]
> I don't understand why the appveyor generated win32 wheels are uploaded successfully. They don't include any long_description either...

I don't know...  Do you feel this needs to be resolved first?

**Comment by altendky** [comment]
> A small note: licence is not displayed correctly on pypi.org.

Hmm, so it's a symlink and I'm guessing that's not being handled right on Windows which is where packages have been uploaded from so far.  I'm not sure about the proper solution across platforms with git and symlinks, but we could just reference `../LICENSE` directly in `setup.py`.

**Comment by miniupnp** [comment]
> > I don't understand why the appveyor generated win32 wheels are uploaded successfully. They don't include any long_description either...
> 
> I don't know... Do you feel this needs to be resolved first?

no :)

I think I have fixed the symlink problem with [3280f12](https://github.com/transmission/miniupnpc/commit/3280f12e3602a56693ab6a9571d2356f8b9f2cff)

**Comment by miniupnp** [comment]
it looks good now !
https://pypi.org/project/miniupnpc/#files

**Pull request closed without merging**
