### PR TITLE
minissdpd improvements 

### PR DESCRIPTION
**Pull request by miniupnp**

### CODE REVIEW

**Comment by miniupnp** [comment]
@hobbieman could you test if your issue is fixed with this branch ?

**Comment by miniupnp** [comment]
@emojifreak hello could you test this branch of minissdpd ?
You'll need to "patch" config.h to enable the "no background, no pid file" build

**Comment by emojifreak** [comment]
> @emojifreak hello could you test this branch of minissdpd ?
> You'll need to "patch" config.h to enable the "no background, no pid file" build

I have run the branch  issue-464 for past two hours, and I have not seen #414 nor #470.

**Comment by emojifreak** [comment]
Sorry, I forgot adding `-6`, and with `-6` I still see `ssdpDiscover: sendto: Cannot assign requested address`.

**Comment by emojifreak** [comment]
With `-6`, I have also seen `Jun 08 19:35:13 router1 minissdpd[23975]: setsockopt(udp, IPV6_JOIN_GROUP)(FF02::C, myve1): Address already in use`. @miniupnp

**Comment by miniupnp** [comment]
> With `-6`, I have also seen `Jun 08 19:35:13 router1 minissdpd[23975]: setsockopt(udp, IPV6_JOIN_GROUP)(FF02::C, myve1): Address already in use`. @miniupnp

the interface `myve1` probably doesn't support IPv6 multicast

**Comment by hobbieman** [comment]
Hi. Sorry, I had not checked on this thread.  I can test #473 as requested, but I need instructions on exactly how to get an executable that includes that fix.

**Comment by bsd-source** [comment]
hobbieman create a fork the miniupnp repository. make your code changes and commit the changes it to your own forked repository. you can git pull the information or download the source code as zip file.

**Comment by hobbieman** [comment]
@miniupnp : Thanks for the detailed instructions!  Indeed I had not checked out the correct branch of code.

I have done that now, compiled and tested and can confirm that minissdpd behaves correctly when the "-i" option is passed.  Specifically, it only sends the SSDP SEARCH on the given interface and it recognizes all the NOTIFY responses from the devices.  Thanks!

**Pull request merged**
