### PR TITLE
deploys to pypi automatically

### PR DESCRIPTION
**Pull request by mrx23dot**
In appveyor added a last step to deploy to pypi automatically.
It uses my credentials, if you want future proofing 

- registers on pypi, 
- send me your username, I will grant you permission
- override credentials in yml, generate secure password in appveyor/account/encrypt

### CODE REVIEW

**Comment by mrx23dot** [comment]
solves https://github.com/miniupnp/miniupnp/issues/570#issuecomment-939786237

**Comment by miniupnp** [comment]
@mrx23dot I finally confirmed my main email

**Comment by miniupnp** [comment]
@mrx23dot have you granted me permission ?

**Comment by miniupnp** [comment]
@mrx23dot I just accepted ;) what do I need to do next ?

**Pull request closed without merging**
