### PR TITLE
minissdpc: add a libuv client

### PR DESCRIPTION
**Pull request by alkino**
Here is a quick&dirty but working implementation of the minissdp client with libuv to have an asynchronous client.

What do you think about it? Mergeable? Useful?

### CODE REVIEW

**Comment by miniupnp** [comment]
please add a README file in the directory to explain

**Comment by alkino** [comment]
Do you mean I should put it in a single directory near libevent?

**Comment by miniupnp** [comment]
> Do you mean I should put it in a single directory near libevent?
>
Well you just add two files without explaining anything.
How to use them ? why ?

**Comment by alkino** [comment]
Here is an update in a separated dir with a README and an example usage file.

**Pull request merged**
