### PR TITLE
fixes of NFTABLES pinout support

### PR DESCRIPTION
**Pull request by miniupnp**
see #663

### CODE REVIEW

**Comment by svenauhagen** [comment]
@miniupnp I will test ipv6 next week for this PR but it looks good. On ipv4 it still works as expected.

**Comment by miniupnp** [comment]
I have rebased on master.
@svenauhagen @juampe thank you for your testing ;)

**Comment by miniupnp** [comment]
it looks like github doesn't see that I have rebased and force pushed the branch

**Pull request merged**
