### PR TITLE
pf nat rules

### PR DESCRIPTION
**Pull request by miniupnp**
still to be done : 
* error checking
* removal of `nat` rule

### CODE REVIEW

**Comment by miniupnp** [comment]
see https://redmine.pfsense.org/issues/7727

**Comment by miniupnp** [comment]
```
nat quick on ep0 inet proto udp from 192.168.1.125 port = 1234 to any keep state label "test description" -> 42.42.42.42 port 12123

rdr pass quick on ep0 inet proto udp from any to any port = 12123 keep state label "test description" -> 192.168.1.125 port 1234
```

**Comment by jim-p** [comment]
Copying my note here from the pfSense Redmine issue:

I don't have two identical consoles with identical online games to test, but just testing with a UPnP client I see the extra NAT rules for UDP and they appear to be correct, though I see two rules instead of the one I'd expect, but the labels are different:

```
miniupnpd rules/nat contents:
nat log quick on igb2 inet proto udp from 192.0.2.87 port = 62322 to any keep state label "NAT-PMP 62322 udp" rtable 0 -> 192.xxx.xxx.111 port 62322
nat log quick on igb2 inet proto udp from 192.0.2.87 port = 62322 to any keep state label "192.0.2.87:62322" rtable 0 -> 192.xxx.xxx.111 port 62322
rdr log quick on igb2 inet proto tcp from any to any port = 62322 keep state label "192.0.2.87:62322" rtable 0 -> 192.0.2.87 port 62322
rdr log quick on igb2 inet proto udp from any to any port = 62322 keep state label "192.0.2.87:62322" rtable 0 -> 192.0.2.87 port 62322
pass in log quick on igb2 inet proto tcp from any to 192.0.2.87 port = 62322 flags S/SA keep state label "192.0.2.87:62322" rtable 0
pass in log quick on igb2 inet proto udp from any to 192.0.2.87 port = 62322 flags S/SA keep state label "192.0.2.87:62322" rtable 0
```

The client opened both a TCP and UDP forward for the same port, and as expected only the UDP one was reflected in the outbound NAT rule. Not sure where the second one came from but since it's labeled NAT-PMP it's different from all the others.

**Comment by miniupnp** [comment]
@jim-p that is strange.. could you test again after disabling NAT-PMP ?

**Comment by jim-p** [comment]
> @jim-p that is strange.. could you test again after disabling NAT-PMP ?

With NAT-PMP disabled, I only see one of the outbound NAT (`nat`) rules.

**Comment by miniupnp** [comment]
it looks OK, but then there is an issue with NAT-PMP

**Comment by miniupnp** [comment]
I'm going to merge, I'll fix if I have feedback

**Comment by bsd-source** [comment]
I would like to provide the information you need to help make this work properly. I've established a minimal basic pfSense 2.5.0 snapshot setup strictly using IPv4. I'm using miniupnpd 2.2.0-RC1 on pfSense. There are 2 Xbox consoles and a Laptop connected to my LAN network and nothing else.

cable modem (dhcp dynamic WAN address) --> pfSense (10.200.200.1) --> wireless access point (10.200.200.2)

Xbox One: Static IP 10.200.200.101
Xbox One: Static IP 10.200.200.102
Laptop: Static IP 10.200.200.103

I tested this and I'm able to obtain open NAT for Xbox Live on both console. But it's required that I setup outbound static-ports for both Xbox's otherwise I don't get an open NAT for Xbox Live on either console.

I need to know the exact tcpdump command you want me to use on pfSense so that I can capture the information you need or any other information you want me to collect so I can provide it to you. That way you can look at the information using wireshark or another program determine what is going on. I know this has been a sore subject since you've had some rude interactions with a select individual. Hopefully you can find the motivation to ignore the past and look forward to helping get miniupnpd working properly with FreeBSD based firewalls.

Please let me know. And that you for a great project.

bsd-source

**Comment by miniupnp** [comment]
@bsd-source 
could you be more explicit on what you need to setup manually for both XBOXs to report open NAT ?
please provide dump of pf rules (pfctl -s rules / pfctl -s nat)
and also the output of `upnpc -l` run from the laptop

**Comment by bsd-source** [comment]
> could you be more explicit on what you need to setup manually for both XBOXs to report open NAT ?

- pfsense - create static dhcpd reservervation for Xbox 1 (10.200.200.101) and Xbox 2 (10.200.200.102).
- pfsense - create one outbound NAT rule with static-ports for IP 10.200.200.101 and one for 10.200.200.102.
- pfsense - enable miniupnpd and create 2 miniupnpd permission rules:
          allow 0-65535 10.200.200.101/32 0-65535
          allow 0-65535 10.200.200.102/32 0-65535

-  Xboxes - setup Xbox 1 with static IP address 10.200.200.101. set Xbox 2 with static IP address 10.200.200.101.
-  Xboxes - setup Xbox 1 with alternate static port 56450. set Xbox 2 with alternate static port 53063. (Note: In 2017 Microsoft made it possible on Xboxes to create and alternate port from the original default port).

The above settings will allow both my Xboxes to have open NAT for *Xbox LIve services*. Although, having an open NAT for Xbox Live services doesn't have anything to do with having and open NAT for gaming.

>please provide dump of pf rules (pfctl -s rules / pfctl -s nat)
>and also the output of upnpc -l run from the laptop

I'm going to email you a zip file containing the following:

1. pfctl -s rules output
2. pfctl -s nat ouput
3. pfSsh.php playback pfanchordrill output
4. upnpc -l output
5. miniupnpd debug mode output
6. miniupnpd.conf file
7. explorted pfsense configuration file
8. 2 images showing both of my Xbox settings

The information I'm sending is without static-ports set in pfsense and then with static-ports set in pfsense. I tested both ways and provided the all the above information for both tests. I don't want to provide the informatoin here as I would need to redact too much information.

**Comment by rchenzheng** [comment]
> > could you be more explicit on what you need to setup manually for both XBOXs to report open NAT ?
> 
> 
> 
> - pfsense - create static dhcpd reservervation for Xbox 1 (10.200.200.101) and Xbox 2 (10.200.200.102).
> 
> - pfsense - create one outbound NAT rule with static-ports for IP 10.200.200.101 and one for 10.200.200.102.
> 
> - pfsense - enable miniupnpd and create 2 miniupnpd permission rules:
> 
>           allow 0-65535 10.200.200.101/32 0-65535
> 
>           allow 0-65535 10.200.200.102/32 0-65535
> 
> 
> 
> -  Xboxes - setup Xbox 1 with static IP address 10.200.200.101. set Xbox 2 with static IP address 10.200.200.101.
> 
> -  Xboxes - setup Xbox 1 with alternate static port 56450. set Xbox 2 with alternate static port 53063. (Note: In 2017 Microsoft made it possible on Xboxes to create and alternate port from the original default port).
> 
> 
> 
> The above settings will allow both my Xboxes to have open NAT for *Xbox LIve services*. Although, having an open NAT for Xbox Live services doesn't have anything to do with having and open NAT for gaming.
> 
> 
> 
> >please provide dump of pf rules (pfctl -s rules / pfctl -s nat)
> 
> >and also the output of upnpc -l run from the laptop
> 
> 
> 
> I'm going to email you a zip file containing the following:
> 
> 
> 
> 1. pfctl -s rules output
> 
> 2. pfctl -s nat ouput
> 
> 3. pfSsh.php playback pfanchordrill output
> 
> 4. upnpc -l output
> 
> 5. miniupnpd debug mode output
> 
> 6. miniupnpd.conf file
> 
> 7. my exported pfsense configuration file
> 
> 8. 2 images showing both of my Xbox settings
> 
> 
> 
> The information I'm sending is without static-ports set in pfsense and then with static-ports set in pfsense. I tested both ways and provided the all the above information for both tests. I don't want to provide the informatoin here as I would need to redact too much information.
> 
>  

I tried this but in PC, still moderate NAT

**Pull request merged**
