### PR TITLE
Fix compilation with i586-mingw32msvc-gcc compiler

### PR DESCRIPTION
**Pull request by pali**
Add also i586-mingw32msvc-gcc cross-compile builds to Travis CI.

### CODE REVIEW

**Comment by pali** [comment]
Hm... seems that build on Travis was not started...

**Comment by miniupnp** [comment]
By the way, I'm trying to add github workflows/Actions now

**Comment by pali** [comment]
So you have disabled Travis?

**Comment by miniupnp** [comment]
I guess travis is disabled automatically, because I have done nothing on travis configuration

**Comment by Faless** [comment]
This breaks UWP compatibility since `GetBestInterface` is only available for desktop apps:
[GetBestInterfaceEx](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getbestinterfaceex#requirements)
[GetBestInterface](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getbestinterface#requirements)

**Pull request merged**
