### PR TITLE
improve netfilter_nft code

### LINKED ISSUE #474: erreur at shutdown
When I shut down I saw the following message. The binary was compiled without SAN checkers. The message seems related to the LSAN error previously discussed.

```
Jun 07 08:19:55 router1 systemd[1]: Stopping UPnP Internet Gateway Device Daemon...
Jun 07 08:19:55 router1 miniupnpd[614]: shutting down MiniUPnPd
Jun 07 08:19:55 router1 miniupnpd[614]: mnl_cb_run() FAILED: No such file or directory
Jun 07 08:19:55 router1 miniupnpd[614]: mnl_cb_run() FAILED: No such file or directory
```

_Originally posted by @emojifreak in https://github.com/miniupnp/miniupnp/issues/468#issuecomment-640132882_

### PR DESCRIPTION
**Pull request by miniupnp**
should fix #474

### CODE REVIEW

**Comment by emojifreak** [comment]
Thank you. I did not observe #474 with the branch `issue-474`. LSAN error remains as below:

```
Jun 08 16:18:34 router1 miniupnpd[22922]: shutting down MiniUPnPd
Jun 08 16:18:34 router1 systemd[1]: Stopping UPnP Internet Gateway Device Daemon...
Jun 08 16:18:34 router1 miniupnpd[22922]: =================================================================
Jun 08 16:18:34 router1 miniupnpd[22922]: ==22922==ERROR: LeakSanitizer: detected memory leaks
Jun 08 16:18:34 router1 miniupnpd[22922]: Direct leak of 32 byte(s) in 2 object(s) allocated from:
Jun 08 16:18:34 router1 miniupnpd[22922]:     #0 0x562f2163d0e2 in calloc (/usr/sbin/miniupnpd+0xf80e2)
Jun 08 16:18:34 router1 miniupnpd[22922]:     #1 0x7ff802c57c62 in nftnl_expr_iter_create (/lib/x86_64-linux-gnu/libnftnl.so.11+0x10c62)
Jun 08 16:18:34 router1 miniupnpd[22922]:     #2 0x7ff802c418ac in mnl_cb_run (/lib/x86_64-linux-gnu/libmnl.so.0+0x28ac)
Jun 08 16:18:34 router1 miniupnpd[22922]: SUMMARY: AddressSanitizer: 32 byte(s) leaked in 2 allocation(s).
```

When miniupnpd is compiled, I observe the following warnings by clang-10:

```
clang-10 -g -fstandalone-debug -ffp-model=strict -fvisibility=hidden -fsanitize=address,undefined,cfi -fno-common -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize-address-use-after-scope -flto -fsanitize-recover=all -c -Os -fno-strict-aliasing -fno-common -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement  -D_GNU_SOURCE -I. -DMINIUPNPD_GIT_REF=\"issue-474-5f66d18\" netfilter_nft/nftpinhole.c -o nftpinhole.o
netfilter_nft/nftpinhole.c:214:7: warning: unused variable 'iaddr'
      [-Wunused-variable]
        char iaddr[INET6_ADDRSTRLEN];
             ^
1 warning generated.

clang-10 -g -fstandalone-debug -ffp-model=strict -fvisibility=hidden -fsanitize=address,undefined,cfi -fno-common -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize-address-use-after-scope -flto -fsanitize-recover=all -c -Os -fno-strict-aliasing -fno-common -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement  -D_GNU_SOURCE -I. -DMINIUPNPD_GIT_REF=\"issue-474-5f66d18\" netfilter_nft/nftnlrdr_misc.c -o nftnlrdr_misc.o
netfilter_nft/nftnlrdr_misc.c:685:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(rule, NFTNL_RULE_TABLE, table);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:686:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(rule, NFTNL_RULE_CHAIN, chain);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:861:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(r, NFTNL_RULE_TABLE, nft_table);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:862:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(r, NFTNL_RULE_CHAIN, nft_postrouting_chain);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:939:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(r, NFTNL_RULE_TABLE, nft_table);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:940:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(r, NFTNL_RULE_CHAIN, nft_prerouting_chain);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:1084:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(r, NFTNL_RULE_TABLE, nft_table);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:1085:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(r, NFTNL_RULE_CHAIN, nft_forward_chain);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:1142:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(r, NFTNL_RULE_TABLE, rule->table);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:1143:2: warning: 'nftnl_rule_set' is deprecated
      [-Wdeprecated-declarations]
        nftnl_rule_set(r, NFTNL_RULE_CHAIN, rule->chain);
        ^
/usr/include/libnftnl/rule.h:38:90: note: 'nftnl_rule_set' has been explicitly
      marked deprecated here
  ...nftnl_rule *r, uint16_t attr, const void *data) __attribute__((deprecat...
                                                                    ^
netfilter_nft/nftnlrdr_misc.c:1267:3: warning: 'nftnl_chain_set' is deprecated
      [-Wdeprecated-declarations]
                nftnl_chain_set(chain, NFTNL_CHAIN_TABLE, table);
                ^
/usr/include/libnftnl/chain.h:42:93: note: 'nftnl_chain_set' has been
      explicitly marked deprecated here
  ...*t, uint16_t attr, const void *data) __attribute__((deprecated));
                                                         ^
netfilter_nft/nftnlrdr_misc.c:1268:3: warning: 'nftnl_chain_set' is deprecated
      [-Wdeprecated-declarations]
                nftnl_chain_set(chain, NFTNL_CHAIN_NAME, name);
                ^
/usr/include/libnftnl/chain.h:42:93: note: 'nftnl_chain_set' has been
      explicitly marked deprecated here
  ...*t, uint16_t attr, const void *data) __attribute__((deprecated));
                                                         ^
12 warnings generated.
```

**Comment by miniupnp** [comment]
@emojifreak could you check if the memory leak is fixed by 92ec4d0 ?

**Comment by miniupnp** [comment]
@emojifreak the deprecations should also be fixed with 86b6aad

**Comment by emojifreak** [comment]
@miniupnp  Yes, the two issues have been fixed. I have not seen the deprecated function errors nor LSAN errors with `-DMINIUPNPD_GIT_REF=\"issue-474-86b6aad\"`

**Pull request merged**
